services:
  - type: web
    name: stegoflask
    runtime: python
    buildCommand: |
      curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar xJ
      mv ffmpeg-*-static/ffmpeg /usr/local/bin/
      chmod +x /usr/local/bin/ffmpeg
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production